/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formal_project;

import java.awt.Color;
import java.awt.Image;
import java.awt.List;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.print.attribute.AttributeSet;
import javax.swing.ImageIcon;
import javax.swing.JTextPane;
import javax.swing.text.*;

/**
 *
 * @author mysterious#2
 */
public class CV_frame_1 extends javax.swing.JFrame {

    /**
     * Creates new form CV_frame_1
     */
    Style defaultStyle;
    Style cwStyle1;
    Style cwStyle2;

    public CV_frame_1() {
        keywordStyle();
        initComponents();
        myDefineMethods();
        String str = "Employment[bkcolor=red,color=black];\n"
                + "Emp_line1[date=10,text=from_egypt1];\n"
                + "Emp_line2[date=20,text=from_egypt2];\n"
                + "Emp_line3[date=30,text=from_egypt3];\n"
                + "Education[bkcolor=yellow,color=red];\n"
                + "Edu_line1[date=40,text=from_egypt4];\n"
                + "Edu_line2[date=50,text=from_egypt5];\n"
                + "Edu_line3[date=60,text=from_egypt6];\n"
                + "Skills[bkcolor=orange,color=white];\n"
                + "Sk_line1[text=java1];\n"
                + "Sk_line2[text=java1];\n"
                + "Sk_line3[text=java1];\n"
                + "Name[text=java1];\n"
                + "Job[text=java1];\n"
                + "Profile[text=java1];\n"
                + "Contact[text=java1];\n"
                + "Hobby[text=java1];\n"
                + "Pro_img[src=C:\\Users\\mysterious#2\\Desktop\\5.jpg];\n";

        boxCode.setText(str);

    }

    private void myDefineMethods() {

        try {
            BufferedImage img = ImageIO.read(new File("C:\\Users\\mysterious#2\\Desktop\\person-icon.png"));
            Image dimg = img.getScaledInstance(lblPImg.getWidth(), lblPImg.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imgIcon = new ImageIcon(dimg);
            lblPImg.setIcon(imgIcon);
        } catch (IOException ex) {
            System.out.println("error is " + ex);
        }

    }

    void keywordStyle() {
        StyleContext styleContext = new StyleContext();
        defaultStyle = styleContext.getStyle(StyleContext.DEFAULT_STYLE);
        cwStyle1 = styleContext.addStyle("ConstantWidth", null);
        StyleConstants.setForeground(cwStyle1, Color.GREEN);
        StyleConstants.setBold(cwStyle1, true);
        cwStyle2 = styleContext.addStyle("ConstantWidth2", null);
        StyleConstants.setForeground(cwStyle2, Color.BLUE);
        StyleConstants.setBold(cwStyle2, true);

        //boxCode=new JTextPane(new KeywordStyledDocument(defaultStyle, cwStyle));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        boxCode = new JTextPane(new KeywordStyledDocument(defaultStyle,cwStyle1,cwStyle2));
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblPImg = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        emp_panel = new javax.swing.JPanel();
        emp_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edu_panel = new javax.swing.JPanel();
        edu_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sk_panel = new javax.swing.JPanel();
        sk_label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emp_date1 = new javax.swing.JLabel();
        emp_text1 = new javax.swing.JLabel();
        emp_text2 = new javax.swing.JLabel();
        emp_date2 = new javax.swing.JLabel();
        emp_text3 = new javax.swing.JLabel();
        emp_date3 = new javax.swing.JLabel();
        edu_text1 = new javax.swing.JLabel();
        edu_date1 = new javax.swing.JLabel();
        edu_text2 = new javax.swing.JLabel();
        edu_date2 = new javax.swing.JLabel();
        edu_text3 = new javax.swing.JLabel();
        edu_date3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        sk_text1 = new javax.swing.JLabel();
        sk_text3 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        sk_text2 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        sk_text4 = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        job_lbl = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hob_lbl = new javax.swing.JLabel();
        pro_lbl = new javax.swing.JLabel();
        con_lbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelError = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_out = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Write your code to edit CV here:");

        boxCode.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        boxCode.setText("1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17");
        boxCode.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                boxCodeInputMethodTextChanged(evt);
            }
        });
        boxCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                boxCodeKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(boxCode);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Result this for your cv:");

        jPanel3.setBackground(new java.awt.Color(46, 44, 103));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        lblPImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formal_project/person-icon.png"))); // NOI18N
        lblPImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblPImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel4.setBackground(new java.awt.Color(238, 242, 255));

        emp_panel.setBackground(new java.awt.Color(89, 199, 229));

        emp_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emp_label.setForeground(new java.awt.Color(255, 255, 255));
        emp_label.setText("Employment");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formal_project/1340-512.png"))); // NOI18N
        jLabel4.setName(""); // NOI18N

        javax.swing.GroupLayout emp_panelLayout = new javax.swing.GroupLayout(emp_panel);
        emp_panel.setLayout(emp_panelLayout);
        emp_panelLayout.setHorizontalGroup(
            emp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emp_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(emp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        emp_panelLayout.setVerticalGroup(
            emp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emp_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emp_label)
                    .addComponent(jLabel4)))
        );

        edu_panel.setBackground(new java.awt.Color(89, 199, 229));

        edu_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        edu_label.setForeground(new java.awt.Color(255, 255, 255));
        edu_label.setText("Education");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formal_project/hat.png"))); // NOI18N
        jLabel6.setName(""); // NOI18N

        javax.swing.GroupLayout edu_panelLayout = new javax.swing.GroupLayout(edu_panel);
        edu_panel.setLayout(edu_panelLayout);
        edu_panelLayout.setHorizontalGroup(
            edu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edu_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(edu_label, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        edu_panelLayout.setVerticalGroup(
            edu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edu_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(edu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edu_label)
                    .addComponent(jLabel6)))
        );

        sk_panel.setBackground(new java.awt.Color(89, 199, 229));

        sk_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sk_label.setForeground(new java.awt.Color(255, 255, 255));
        sk_label.setText("Skills");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formal_project/star.png"))); // NOI18N
        jLabel8.setName(""); // NOI18N

        javax.swing.GroupLayout sk_panelLayout = new javax.swing.GroupLayout(sk_panel);
        sk_panel.setLayout(sk_panelLayout);
        sk_panelLayout.setHorizontalGroup(
            sk_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sk_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(sk_label, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sk_panelLayout.setVerticalGroup(
            sk_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sk_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sk_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sk_label)
                    .addComponent(jLabel8)))
        );

        emp_date1.setText("2015-2016");

        emp_text1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emp_text1.setForeground(new java.awt.Color(51, 51, 51));
        emp_text1.setText("Web company studio as web developer");

        emp_text2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emp_text2.setForeground(new java.awt.Color(51, 51, 51));
        emp_text2.setText("Web company studio as web developer");

        emp_date2.setText("2015-2016");

        emp_text3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emp_text3.setForeground(new java.awt.Color(51, 51, 51));
        emp_text3.setText("Web company studio as web developer");

        emp_date3.setText("2015-2016");

        edu_text1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edu_text1.setForeground(new java.awt.Color(51, 51, 51));
        edu_text1.setText("university of zagazig  DA student      ");

        edu_date1.setText("2015-2016");

        edu_text2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edu_text2.setForeground(new java.awt.Color(51, 51, 51));
        edu_text2.setText("university of zagazig  DA student      ");

        edu_date2.setText("2015-2016");

        edu_text3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edu_text3.setForeground(new java.awt.Color(51, 51, 51));
        edu_text3.setText("university of zagazig  DA student      ");

        edu_date3.setText("2015-2016");

        jLabel30.setText("Skill(1):");

        sk_text1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sk_text1.setForeground(new java.awt.Color(51, 51, 51));
        sk_text1.setText("HTML /css");

        sk_text3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sk_text3.setForeground(new java.awt.Color(51, 51, 51));
        sk_text3.setText("HTML /css");

        jLabel33.setText("Skill(3):");

        sk_text2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sk_text2.setForeground(new java.awt.Color(51, 51, 51));
        sk_text2.setText("HTML /css");

        jLabel35.setText("Skill(2):");

        jLabel36.setText("Skill(4):");

        sk_text4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sk_text4.setForeground(new java.awt.Color(51, 51, 51));
        sk_text4.setText("HTML /css");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emp_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edu_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sk_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(emp_date1)
                                .addGap(57, 57, 57)
                                .addComponent(emp_text1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(emp_date2)
                                .addGap(57, 57, 57)
                                .addComponent(emp_text2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(emp_date3)
                                .addGap(57, 57, 57)
                                .addComponent(emp_text3))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(edu_date1)
                        .addGap(57, 57, 57)
                        .addComponent(edu_text1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(edu_date2)
                        .addGap(57, 57, 57)
                        .addComponent(edu_text2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(edu_date3)
                        .addGap(57, 57, 57)
                        .addComponent(edu_text3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sk_text3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sk_text1)))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sk_text4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sk_text2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(emp_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_date1)
                    .addComponent(emp_text1))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_date2)
                    .addComponent(emp_text2))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_date3)
                    .addComponent(emp_text3))
                .addGap(53, 53, 53)
                .addComponent(edu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edu_date1)
                    .addComponent(edu_text1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edu_date2)
                    .addComponent(edu_text2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edu_date3)
                    .addComponent(edu_text3))
                .addGap(39, 39, 39)
                .addComponent(sk_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(sk_text1)
                    .addComponent(jLabel35)
                    .addComponent(sk_text2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(sk_text4))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(sk_text3)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        name_lbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        name_lbl.setForeground(new java.awt.Color(255, 255, 255));
        name_lbl.setText("MY NAME");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("_________________");

        job_lbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        job_lbl.setForeground(new java.awt.Color(255, 255, 255));
        job_lbl.setText("Software Engineer");

        jPanel8.setBackground(new java.awt.Color(89, 199, 229));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("profile");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formal_project/hat.png"))); // NOI18N
        jLabel13.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(89, 199, 229));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("contact");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formal_project/hat.png"))); // NOI18N
        jLabel15.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(89, 199, 229));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Hobby");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formal_project/hat.png"))); // NOI18N
        jLabel17.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hob_lbl.setForeground(new java.awt.Color(204, 204, 204));
        hob_lbl.setText("football -swiming -reading-eating");

        pro_lbl.setForeground(new java.awt.Color(204, 204, 204));
        pro_lbl.setText("i live in egypt form 15 year");

        con_lbl.setForeground(new java.awt.Color(204, 204, 204));
        con_lbl.setText("01203874747");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPImg, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name_lbl, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(job_lbl)))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hob_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(pro_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(484, 484, 484)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(con_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(484, 484, 484)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblPImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(job_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hob_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(282, Short.MAX_VALUE)
                    .addComponent(pro_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(258, 258, 258)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(390, Short.MAX_VALUE)
                    .addComponent(con_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(150, 150, 150)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(176, 176, 176))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formal_project/go_arrow_next_up_green_forward-512.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formal_project/drawer-output-512.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        panelError.setBackground(new java.awt.Color(204, 204, 204));

        list_out.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        list_out.setForeground(new java.awt.Color(255, 51, 51));
        list_out.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "errors", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_out);

        javax.swing.GroupLayout panelErrorLayout = new javax.swing.GroupLayout(panelError);
        panelError.setLayout(panelErrorLayout);
        panelErrorLayout.setHorizontalGroup(
            panelErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        panelErrorLayout.setVerticalGroup(
            panelErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelErrorLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formal_project/Save-icon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenu3.setText("new");

        jMenu6.setText("cv1");
        jMenu3.add(jMenu6);

        jMenu7.setText("cv2");
        jMenu3.add(jMenu7);

        jMenu8.setText("cv3");
        jMenu3.add(jMenu8);

        jMenu1.add(jMenu3);

        jMenu4.setText("open");
        jMenu1.add(jMenu4);

        jMenu5.setText("close");
        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu9.setText("Run");
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean panelV = true;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (panelV) {
            panelError.setVisible(false);
            panelV = false;

        } else {
            panelError.setVisible(true);
            panelV = true;
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    ArrayList<String> list = null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int lineError = 0;
        Parser p = new Parser();
        Parser.syntax=true;
        Parser.lookAhead=0;
         

        list = new ArrayList<String>();
        list.add("---------------------OUTPUT------------------------------------");

        String code = boxCode.getText();
        code = code.replaceAll(" ", "");
        code = code.replaceAll("\\n", "");
        //System.out.println(code);
        String[] statments = code.split(";");
        for (String stat : statments) {
            lineError++;
            Parser.msg = stat + ";";
            //System.out.println(Parser.msg);
            p.S();
            if (!Parser.syntax) {
                list.add(Parser.msg);
                break;
                
            }
            Parser.lookAhead=0;

        }
        if (Parser.syntax) {
            for (int x = 0; x < statments.length; x++) {
                String element = statments[x].substring(0, statments[x].indexOf('['));
                //System.out.println(element);
                String blockAtt = statments[x].substring(statments[x].indexOf('[') + 1, statments[x].indexOf(']'));
                //System.out.println(blockAtt);
                String[] attributes = blockAtt.split(",");
                for (String att : attributes) {
                    String property = att.substring(0, att.indexOf('='));
                    String value = att.substring(att.indexOf('=') + 1);
                    String out = "elem--> " + element + "( pro--> " + property + ": val--> " + value + " )";
                    //System.out.println("out is : " + out);
                    control(element, property, value);

                    list.add(out);

                }
            }
            list.add("---------------------DONE---------------------------------------");
            Object[] sts = list.toArray();
            list_out.setForeground(Color.GRAY);

            list_out.setListData(sts);

        }else{
            
            list.add("syntax error at line :("+lineError+")");
            Object[] sts = list.toArray();
            list_out.setForeground(Color.red);
            
            list_out.setListData(sts);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    //methods to change the text color/////////////////////////

    
    private void boxCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxCodeKeyReleased
        

    }//GEN-LAST:event_boxCodeKeyReleased

    private void boxCodeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_boxCodeInputMethodTextChanged
        
    }//GEN-LAST:event_boxCodeInputMethodTextChanged

    public void control(String elem, String pro, String val) {
        CV_class cv = new CV_class();

        switch (elem) {
///////////////////////////////////////////////////////////////center side//////////////////////////////////////
            case "Employment":
                if ("bkcolor".equals(pro)) {
                    Color c = cv.color(val);
                    cv.changeColorPanel(emp_panel, c);

                } else if ("color".equals(pro)) {
                    Color c = cv.color(val);
                    cv.changeColorText(emp_label, c);

                }

                break;
            case "Emp_line1":
                if ("date".equals(pro)) {
                    cv.changeText(emp_date1, val);

                } else if ("text".equals(pro)) {
                    cv.changeText(emp_text1, val);

                }
                break;
            case "Emp_line2":
                if ("date".equals(pro)) {
                    cv.changeText(emp_date2, val);

                } else if ("text".equals(pro)) {
                    cv.changeText(emp_text2, val);

                }
                break;
            case "Emp_line3":
                if ("date".equals(pro)) {
                    cv.changeText(emp_date3, val);

                } else if ("text".equals(pro)) {
                    cv.changeText(emp_text3, val);

                }
                break;
            case "Education":
                if ("bkcolor".equals(pro)) {
                    Color c = cv.color(val);
                    cv.changeColorPanel(edu_panel, c);

                } else if ("color".equals(pro)) {
                    Color c = cv.color(val);
                    cv.changeColorText(edu_label, c);

                }
                break;
            case "Edu_line1":
                if ("date".equals(pro)) {
                    cv.changeText(edu_date1, val);

                } else if ("text".equals(pro)) {
                    cv.changeText(edu_text1, val);

                }
                break;
            case "Edu_line2":
                if ("date".equals(pro)) {
                    cv.changeText(edu_date2, val);

                } else if ("text".equals(pro)) {
                    cv.changeText(edu_text2, val);

                }
                break;
            case "Edu_line3":
                if ("date".equals(pro)) {
                    cv.changeText(edu_date3, val);

                } else if ("text".equals(pro)) {
                    cv.changeText(edu_text3, val);

                }
                break;
            case "Skills":
                if ("bkcolor".equals(pro)) {
                    Color c = cv.color(val);
                    cv.changeColorPanel(sk_panel, c);

                } else if ("color".equals(pro)) {
                    Color c = cv.color(val);
                    cv.changeColorText(sk_label, c);

                }
                break;
            case "Sk_line1":
                if ("text".equals(pro)) {
                    cv.changeText(sk_text1, val);

                }
                break;
            case "Sk_line2":
                if ("text".equals(pro)) {
                    cv.changeText(sk_text2, val);

                }
                break;
            case "Sk_line3":
                if ("text".equals(pro)) {
                    cv.changeText(sk_text3, val);

                }
                break;
            case "Sk_line4":
                if ("text".equals(pro)) {
                    cv.changeText(sk_text4, val);

                }
                break;
/////////////////////////////////////////////////////////////////////////////////lift side ////////////////
            case "Name":
                if ("text".equals(pro)) {
                    cv.changeText(name_lbl, val);

                }
                break;
            case "Job":
                if ("text".equals(pro)) {
                    cv.changeText(job_lbl, val);

                }
                break;
            case "Pro_img":
                if ("src".equals(pro)) {
                    cv.changeImage(lblPImg, val);

                }
                break;
            case "Profile":
                if ("text".equals(pro)) {
                    cv.changeText(pro_lbl, val);

                }
                break;
            case "Contact":
                if ("text".equals(pro)) {
                    cv.changeText(con_lbl, val);

                }
                break;
            case "Hobby":
                if ("text".equals(pro)) {
                    cv.changeText(hob_lbl, val);

                }
                break;

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CV_frame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CV_frame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CV_frame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CV_frame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CV_frame_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane boxCode;
    private javax.swing.JLabel con_lbl;
    private javax.swing.JLabel edu_date1;
    private javax.swing.JLabel edu_date2;
    private javax.swing.JLabel edu_date3;
    private javax.swing.JLabel edu_label;
    private javax.swing.JPanel edu_panel;
    private javax.swing.JLabel edu_text1;
    private javax.swing.JLabel edu_text2;
    private javax.swing.JLabel edu_text3;
    private javax.swing.JLabel emp_date1;
    private javax.swing.JLabel emp_date2;
    private javax.swing.JLabel emp_date3;
    private javax.swing.JLabel emp_label;
    private javax.swing.JPanel emp_panel;
    private javax.swing.JLabel emp_text1;
    private javax.swing.JLabel emp_text2;
    private javax.swing.JLabel emp_text3;
    private javax.swing.JLabel hob_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel job_lbl;
    private javax.swing.JLabel lblPImg;
    private javax.swing.JList list_out;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JPanel panelError;
    private javax.swing.JLabel pro_lbl;
    private javax.swing.JLabel sk_label;
    private javax.swing.JPanel sk_panel;
    private javax.swing.JLabel sk_text1;
    private javax.swing.JLabel sk_text2;
    private javax.swing.JLabel sk_text3;
    private javax.swing.JLabel sk_text4;
    // End of variables declaration//GEN-END:variables
}
